# Generated by Django 3.0.8 on 2020-07-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsedBooks', '0007_auto_20200705_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usedcategory',
            options={'verbose_name': 'Categories for Used Book'},
        ),
        migrations.AlterModelOptions(
            name='usedcomment',
            options={'verbose_name': 'Used Books Comment'},
        ),
        migrations.AlterModelOptions(
            name='usedproduct',
            options={'verbose_name': 'Used Book'},
        ),
        migrations.AlterModelOptions(
            name='usedsubcategory',
            options={'verbose_name': 'Sub Categories for Used Book'},
        ),
    ]
