# Generated by Django 3.0.8 on 2020-07-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_auto_20200705_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Book'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sub Categorie'},
        ),
    ]
